// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coqueiros_modulo1_semana10_exercicio.Model;

#nullable disable

namespace coqueiros_modulo1_semana10_exercicio.Migrations
{
    [DbContext(typeof(LocacaoContext))]
    [Migration("20230410195422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coqueiros_modulo1_semana10_exercicio.Model.CarroModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("coqueiros_modulo1_semana10_exercicio.Model.MarcaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("MarcaModel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("MarcaModel");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("coqueiros_modulo1_semana10_exercicio.Model.MarcaModel", b =>
                {
                    b.HasOne("coqueiros_modulo1_semana10_exercicio.Model.CarroModel", null)
                        .WithMany("Marca")
                        .HasForeignKey("MarcaModel");
                });

            modelBuilder.Entity("coqueiros_modulo1_semana10_exercicio.Model.CarroModel", b =>
                {
                    b.Navigation("Marca");
                });
#pragma warning restore 612, 618
        }
    }
}
